name: Repository Autoupdate

on:
  schedule:
    - cron:  '30 2 * * *'
  workflow_dispatch:

jobs:
  prepare:
    name: Prepare repository
    runs-on: [self-hosted]
    if: ${{ github.repository_owner == 'jethub-homeassistant' }}
    steps:
      - name: Clean git
        run: |
          mkdir -p rebase_haos
          cd rebase_haos
          git remote remove upstream || true
      - name: Checkout jethub haos repository (dev)
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: jethub-homeassistant/operating-system
          path: rebase_haos
          token: ${{ secrets.HA_UPDATE_TOKEN }}
          ref: dev
      - name: Rebase haos repository (dev)
        run: |
          cd rebase_haos
          UPSTREAM=https://github.com/home-assistant/operating-system.git
          git remote add upstream $UPSTREAM  || true
          git fetch upstream dev
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name  "GitHub Actions"
          git rebase upstream/dev
          if [ "$(git status | grep diverged)" ]; then
            git push origin $(git branch --show-current) --force-with-lease;
          else
            git push origin $(git branch --show-current)
          fi;
          git remote remove upstream || true

      - name: Checkout jethub haos repository (dev-jethub)
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: jethub-homeassistant/operating-system
          path: rebase_haos
          token: ${{ secrets.HA_UPDATE_TOKEN }}
          ref: dev-jethub
      - name: Rebase jethub haos repository (dev-jethub)
        run: |
          cd rebase_haos
          git pull
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name  "GitHub Actions"
          git rebase origin/dev
          if [ "$(git status | grep diverged)" ]; then
            git push origin $(git branch --show-current) --force-with-lease;
          else
            git push origin $(git branch --show-current)
          fi;
